"""Example of a VQE calc using Qiskit-Nature and data loaded from file.

H2 data generated from a RHF/sto-3g calculation using DIRAC-ASE calculator.
"""

import os

from qiskit_algorithms.optimizers import SLSQP
from qiskit.primitives import Estimator

from qc2.data import qc2Data
from qc2.algorithms.qiskit import VQE
from qc2.algorithms.utils import ActiveSpace


# file generated by any ASE calculator implemented in qc2
hdf5_file = "datafiles/qc2-qcschema_format_file_to_load_h2_data.hdf5"

# check that the file exists
if not os.path.exists(hdf5_file):
    raise FileNotFoundError(f"{hdf5_file} file not found")

# init the hdf5 file
qc2data = qc2Data(hdf5_file, schema="qcschema")

# define activate space
n_active_electrons = (1, 1)  # => (n_alpha, n_beta)
n_active_spatial_orbitals = 2

# set up VQE calc
qc2data.algorithm = VQE(
    active_space=ActiveSpace(
        num_active_electrons=(1, 1), num_active_spatial_orbitals=2
    ),
    optimizer=SLSQP(),
    estimator=Estimator(),
)

# run the calc
result = qc2data.algorithm.run()
